export const items =  [
    {
        id: 1,
        category: 'watches',
        title: "Apple Watch Ultra",
        imgSrc: 'https://m.media-amazon.com/images/I/51Qz6ox0yeL._SX300_SY300_QL70_FMwebp_.jpg',
        description: 'Apple Watch Ultra [GPS + Cellular]',
        price: '63990',
        qty: '0',
      },
    {
      id: 2,
      category: 'smartphones',
      title: "Apple iPhone 15 Pro Max",
      imgSrc: 'https://m.media-amazon.com/images/I/81Os1SDWpcL._SX679_.jpg',
      description: 'Apple iPhone 15 Pro Max (256 GB)',
      price: '148900',
      qty: '0',
    },
    {
        id: 4,
        category: 'laptops',
        title: "Lenovo IdeaPad Slim 5 ",
        imgSrc: 'https://m.media-amazon.com/images/I/518BYF8LHRL._SX679_.jpg',
        description: 'Lenovo IdeaPad Slim 5 Intel Core i5',
        price: '29999',
        qty: '0',
      },
    {
      id: 5,
      category: 'laptops',
      title: "Xiaomi [Smartchoice]",
      imgSrc: 'https://m.media-amazon.com/images/I/713he67k8HL._SX679_.jpg',
      description: 'Xiaomi [Smartchoice] Notebookpro ',
      price: '49999',
      qty: '0',
    },
    {
      id: 7,
      category: 'tablets',
      title: "Xiaomi Pad 6",
      imgSrc: 'https://m.media-amazon.com/images/I/41uBZTsvRSL._SX300_SY300_QL70_FMwebp_.jpg',
      description: 'Xiaomi Pad 6| Qualcomm',
      price: '29999',
      qty: '0',
    },
    {
        id: 12,
        category: 'smartphones',
        title: "Apple iPhone 14",
        imgSrc: 'https://m.media-amazon.com/images/I/71xb2xkN5qL._SL1500_.jpg',
        description: 'Apple iPhone 14 (128 GB) - Blue',
        price: '62800',
        qty: '0',
    },
    {
      id: 6,
      category: 'tablets',
      title: "Lenovo Tab P12 Pro",
      imgSrc: 'https://m.media-amazon.com/images/I/51vXqMcfwyL._SX679_.jpg',
      description: 'Lenovo Tab P12 Pro AMOLED #most trusted brand',
      price: '19999',
      qty: '0',
    },
    {
      id: 3,
      category: 'smartphones',
      title: "Apple iPhone 13",
      imgSrc: 'https://m.media-amazon.com/images/I/71GLMJ7TQiL._SX679_.jpg',
      description: 'Apple iPhone 13 (128GB) - White',
      price: '55090',
      qty: '0',
    },
    
    {
      id: 9,
      category: 'tablets',
      title: "Samsung Galaxy Tab A8",
      imgSrc: 'https://m.media-amazon.com/images/I/71LviO0dvIL._SX679_.jpg',
      description: 'Samsung Galaxy Tab A8 26.69cm',
      price: '49999',
      qty: '0',
    },
    {
      id: 8,
      category: 'laptops',
      title: "Apple MacBook Air Laptop",
      imgSrc: 'https://m.media-amazon.com/images/I/71TPda7cwUL._SL1500_.jpg',
      description: 'Apple MacBook Air Laptop M1 chip, 13.3-inch/33.74 cm Retina Display, ',
      price: '89999',
      qty: '0',
    },
    {
        id: 10,
        category: 'watches',
        title: "Apple Smartwatch SE",
        imgSrc: 'https://m.media-amazon.com/images/I/61rTufzD1zL._SX679_.jpg',
        description: 'Apple Watch SE (2nd Gen, 2023) [GPS 40mm] Smartwatch',
        price: '27999',
        qty: '0',
      },
      {
        id: 11,
        category: 'watches',
        title: "Samsung Galaxy Watch6",
        imgSrc: 'https://m.media-amazon.com/images/I/410EFEms7pL._SX300_SY300_QL70_FMwebp_.jpg',
        description: 'Samsung Galaxy Watch6 Bluetooth (40mm, Gold) smart watch',
        price: '24749',
        qty: '0',
      },


  ]